spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: murad123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation : true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
ms:
  url: /employee-ms


server:
  port: 8081
